name: Tests Runner

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose v2
        uses: docker/setup-docker-action@v4

      - name: Run Tests
        run: docker compose run -T test pytest --cov=src --cov-report=term
